const CityActionTypes = {
    SEARCH_CITY: 'SEARCH_CITY',
    FETCH_CITIES_START: 'FETCH_CITIES_START',
    FETCH_CITIES_SUCCESS: 'FETCH_CITIES_SUCCESS',
    FETCH_CITIES_FAILURE: 'FETCH_CITIES_FAILURE',
    SET_SELECTED_CITY: 'SET_SELECTED_CITY'
}

export default CityActionTypes;