const WeatherActionTypes = {
    CURRENT_WEATHER: 'CURRENT_WEATHER',
    FETCH_CURRENT_WEATHER_START: 'FETCH_CURRENT_WEATHER_START',
    FETCH_CURRENT_WEATHER_SUCCESS: 'FETCH_CURRENT_WEATHER_SUCCESS',
    FETCH_CURRENT_WEATHER_FAILURE: 'FETCH_CURRENT_WEATHER_FAILURE',
}

export default WeatherActionTypes;