const WeatherActionTypes = {
    CURRENT_WEATHER: 'CURRENT_WEATHER',
    FETCH_CURRENT_WEATHER_START: 'FETCH_CURRENT_WEATHER_START',
    FETCH_CURRENT_WEATHER_SUCCESS: 'FETCH_CURRENT_WEATHER_SUCCESS',
    FETCH_CURRENT_WEATHER_FAILURE: 'FETCH_CURRENT_WEATHER_FAILURE',
    // FETCH_FIVE_DAYS_FORECAT_START: 'FETCH_FIVE_DAYS_FORECAT_START',
    // FETCH_FIVE_DAYS_FORECAT_SUCCESS: 'FETCH_FIVE_DAYS_FORECAT_SUCCESS',
    // FETCH_FIVE_DAYS_FORECAT_FAILURE: 'FETCH_FIVE_DAYS_FORECAT_FAILURE'
}

export default WeatherActionTypes;