const ForecastActionTypes = {
    FETCH_FIVE_DAYS_FORECAT_START: 'FETCH_FIVE_DAYS_FORECAT_START',
    FETCH_FIVE_DAYS_FORECAT_SUCCESS: 'FETCH_FIVE_DAYS_FORECAT_SUCCESS',
    FETCH_FIVE_DAYS_FORECAT_FAILURE: 'FETCH_FIVE_DAYS_FORECAT_FAILURE'
}

export default ForecastActionTypes;