const FavoritesActionTypes = {
    IS_EXIST_IN_FAV_LIST: 'IS_EXIST_IN_FAV_LIST',
    SHOW_FAVORITES_TO_PAGE: 'SHOW_FAVORITES_TO_PAGE',
    ADD_TO_FAVORITES_LIST: 'ADD_TO_FAVORITES_LIST',
    REMOVE_FROM_FAVORITES_LIST: 'REMOVE_FROM_FAVORITES_LIST'
};

export default  FavoritesActionTypes;